---
title: "R Notebook"
output: html_notebook
---


```{r}
setwd('Documents/Github/math189/hw2/')
```
```{r}
video <- read.table('videodata.txt', header = TRUE)
videoMulti <- read.table('videoMultiple.txt', header = TRUE)
head(video)
head(videoMulti)
```
```{r}
library(ggplot2)
time <- video$time
ggplot(video, aes(time))+geom_histogram()
```


```{r}
sqsum = 0
for (i in time) {
  sqsum <- sqsum + (i-mean(time))^2
}
sqS = sqsum/(length(time)-1)
varEst = sqrt(sqS*(313/314))
a <- varEst/sqrt(91)
ciL <- mean(time) - 2*a
ciR <- mean(time) + 2*a
qplot(time, geom='histogram') + geom_vline(aes(xintercept=ciL), color = 'red') + geom_vline(aes(xintercept=ciR), color = 'red')

ciL
ciR
```



```{r}
bootobj = NULL
n <- 400
for ( i in 1:n) {
  bootobj[i] = mean (sample(as.vector(rep(time, times=4)), size = 91, replace = TRUE))
}
quantile(bootobj, c(.025, .975))
qplot(bootobj, geom='histogram') 

```


```{r}
library(moments)
bootSkew <- skewness(bootobj)
bootKurt <- kurtosis(bootobj)
bootSkew
bootKurt
```


```{r}
par(pty = 's') # plot in a square
qqnorm(bootobj)
qqline(bootobj)
```

```{r}
kurt = NULL
for (i in 1:1000){
  kurt[i] = kurtosis(rnorm(n))
}
skew = NULL
for (i in 1:1000){
  skew[i] = skewness(rnorm(n))
}

qplot(kurt, geom = 'histogram') + geom_vline(aes(xintercept=bootKurt), color = 'red')
qplot(skew, geom = 'histogram') + geom_vline(aes(xintercept=bootSkew), color = 'red')

p_kurt <- mean(kurt > bootKurt)
p_skew <- mean(skew > bootSkew)
p_kurt
p_skew
```


```{r}
att=video$like
resp_att <- att[!att == 99]
qplot(resp_att, geom = 'histogram')
mean(resp_att)

```

```{r}
copy <- data.frame(videoMulti)
copy$like <- video$like
copy$other <- NULL
copy$other2 <- NULL
copy <- copy[complete.cases(copy),6:20]
copy
```

```{r}
never <- copy[copy$like==1,]
very <- copy[copy$like==2,]
somewhat <- copy[copy$like==3,]
notReally <- copy[copy$like==4,]
no <- copy[copy$like==5,]
noResp <- copy[copy$like==99,]
```

```{r}
dislike <- rbind(no, never)
df <- data.frame(t(data.frame(colMeans(very), colMeans(somewhat), colMeans(notReally), colMeans(dislike))))
df$like <- NULL
rLike <- df[,1:5]
rDislike <- df[,5:14]
```

```{r}
resp <- colnames(df)

barplot(as.matrix(rLike), las=2,
main = "Percentage of people agreed with each reason of liking video games",
col = c("red","green", "blue"),
)
legend(x = "topright", bty = "n", cex=0.5,
c("Very Much","Somewhat","Not Really"),
fill = c("red","green","blue")
)
barplot(as.matrix(rDislike), las=2,
main = "Percentage of people agreed with each reason of disliking video games",
col = c("red","green", "blue", "yellow"),
)
legend(x = "topleft", bty = "n", cex=0.5,
c("Very Much","Somewhat","Not Really", "Not At All or never played"),
fill = c("red","green","blue", "yellow")
)
```


